#!/usr/bin/env python3
"""Standalone preflight validator for designed CV text elements; not a raster substitute."""
import json, argparse, sys
from pathlib import Path

FORBIDDEN = ("premium cv", "application updated:", "generated by ai", "agent notes", "lorem ipsum", "name surname")

def check(document):
    errors=[]
    page_count=document.get("page_count", 0)
    if not isinstance(page_count,int) or page_count not in (1,2,3): errors.append("invalid_page_count")
    for i, p in enumerate(document.get("pages",[])):
        width,height=p.get("width",0),p.get("height",0)
        elements=p.get("text_elements",[])
        for j,e in enumerate(elements):
            x,y,w,h=[e.get(k,0) for k in ("x","y","w","h")]
            label=f"page{i+1}:text{j+1}"
            if w<=0 or h<=0 or x<0 or y<0 or x+w>width+1e-5 or y+h>height+1e-5: errors.append(label+":out_of_page")
            txt=str(e.get("text",""))
            if any(t in txt.casefold() for t in FORBIDDEN): errors.append(label+":unapproved_note")
            if e.get("font_pt",0)<9 and e.get("kind","body") not in ("page_number","caption"): errors.append(label+":undersize")
        for j,a in enumerate(elements):
            for k,b in enumerate(elements[j+1:],j+1):
                if a.get("allow_overlap") or b.get("allow_overlap"): continue
                if all(q in a for q in ("x","y","w","h")) and all(q in b for q in ("x","y","w","h")):
                    ow=min(a['x']+a['w'],b['x']+b['w'])-max(a['x'],b['x'])
                    oh=min(a['y']+a['h'],b['y']+b['h'])-max(a['y'],b['y'])
                    if ow>1e-4 and oh>1e-4: errors.append(f"page{i+1}:text{j+1}:text{k+1}:overlap")
    if len(document.get('pages',[]))!=page_count:errors.append("page_count_mismatch")
    return errors

if __name__=='__main__':
    parser=argparse.ArgumentParser();parser.add_argument('layout_json',type=Path);a=parser.parse_args()
    errors=check(json.loads(a.layout_json.read_text()))
    print(json.dumps({'passed':not errors,'errors':errors},indent=2));sys.exit(bool(errors))
