const VERSION = "0.1.0";
const MAX_BYTES = 6 * 1024 * 1024;
const DEFAULT_TTL = 600;
const MAX_TTL = 1800;
const ALLOWED = new Set(["image/png", "image/jpeg"]);
const enc = new TextEncoder();
function json(data, status = 200, headers = {}) { return new Response(JSON.stringify(data), { status, headers: { "content-type": "application/json; charset=utf-8", "cache-control": "no-store", ...headers } }); }
function base64ToBytes(value) { const clean = String(value || "").replace(/\s+/g, ""); const binary = atob(clean); const out = new Uint8Array(binary.length); for (let i = 0; i < binary.length; i++) out[i] = binary.charCodeAt(i); return out; }
function hex(buffer) { return [...new Uint8Array(buffer)].map(b => b.toString(16).padStart(2, "0")).join(""); }
function safeEqual(a, b) { if (a.length !== b.length) return false; let x = 0; for (let i = 0; i < a.length; i++) x |= a.charCodeAt(i) ^ b.charCodeAt(i); return x === 0; }
async function sign(secret, value) { const key = await crypto.subtle.importKey("raw", enc.encode(secret), { name: "HMAC", hash: "SHA-256" }, false, ["sign"]); return hex(await crypto.subtle.sign("HMAC", key, enc.encode(value))); }
function requireAdmin(request, env) { const value = request.headers.get("authorization") || ""; if (!value.startsWith("Bearer ") || !safeEqual(value.slice(7), env.ADMIN_TOKEN || "")) throw new Response("unauthorized", { status: 401 }); }
function mediaKey(id) { return `media:${id}`; }
export default { async fetch(request, env) { try { const url = new URL(request.url);
if (request.method === "GET" && url.pathname === "/health") return json({ ok: true, service: "dedal-media-staging", version: VERSION });
if (request.method === "POST" && url.pathname === "/v1/stage") { requireAdmin(request, env); const body = await request.json().catch(() => null); if (!body || typeof body.content_base64 !== "string") return json({ error: "content_base64_required" }, 400); const contentType = String(body.content_type || "").toLowerCase(); if (!ALLOWED.has(contentType)) return json({ error: "unsupported_media_type", allowed: [...ALLOWED] }, 415); let bytes; try { bytes = base64ToBytes(body.content_base64); } catch { return json({ error: "invalid_base64" }, 400); } if (!bytes.byteLength || bytes.byteLength > MAX_BYTES) return json({ error: "media_too_large", max_bytes: MAX_BYTES }, 413); const ttl = Math.max(60, Math.min(MAX_TTL, Number(body.ttl_seconds) || DEFAULT_TTL)); const id = crypto.randomUUID(); const key = mediaKey(id); const now = Math.floor(Date.now() / 1000); const expiresAt = now + ttl; const sha256 = hex(await crypto.subtle.digest("SHA-256", bytes)); await env.MEDIA.put(key, bytes, { expirationTtl: ttl, metadata: { content_type: contentType, bytes: bytes.byteLength, sha256, created_at: now, expires_at: expiresAt } }); const signature = await sign(env.SIGNING_SECRET, `${key}\n${expiresAt}`); const sourceUrl = `${url.origin}/m/${encodeURIComponent(id)}?exp=${expiresAt}&sig=${signature}`; return json({ stage_id: id, source_url: sourceUrl, expires_at: expiresAt, ttl_seconds: ttl, content_type: contentType, bytes: bytes.byteLength, sha256 }, 201); }
const media = url.pathname.match(/^\/m\/([0-9a-f-]{36})$/i); if (media && (request.method === "GET" || request.method === "HEAD")) { const id = media[1]; const key = mediaKey(id); const exp = Number(url.searchParams.get("exp") || 0); const signature = String(url.searchParams.get("sig") || ""); const now = Math.floor(Date.now() / 1000); if (!exp || exp < now || exp > now + MAX_TTL + 60) return new Response("expired", { status: 403 }); const expected = await sign(env.SIGNING_SECRET, `${key}\n${exp}`); if (!safeEqual(signature, expected)) return new Response("forbidden", { status: 403 }); const object = await env.MEDIA.getWithMetadata(key, { type: "arrayBuffer" }); if (!object.value) return new Response("not found", { status: 404 }); const metadata = object.metadata || {}; const headers = { "content-type": metadata.content_type || "application/octet-stream", "cache-control": "private, no-store, max-age=0", "x-content-type-options": "nosniff", "content-length": String(metadata.bytes || object.value.byteLength) }; return request.method === "HEAD" ? new Response(null, { status: 200, headers }) : new Response(object.value, { status: 200, headers }); }
const deletion = url.pathname.match(/^\/v1\/stage\/([0-9a-f-]{36})$/i); if (deletion && request.method === "DELETE") { requireAdmin(request, env); await env.MEDIA.delete(mediaKey(deletion[1])); return json({ deleted: true, stage_id: deletion[1] }); }
return json({ error: "not_found" }, 404); } catch (error) { if (error instanceof Response) return error; return json({ error: "internal_error" }, 500); } } };
